//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uslugi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServiceNew
    {
        public int ID { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string Servise { get; set; }
    }
}
